config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end

  namespace :admin do
    resources :restaurants, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, :inclusion => { :in => 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = current_user.restaurants
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/admin/controller_helper.rb
module Admin::ControllerHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">

  <div class="title">
    <h1><strong>Edit the Restaurant</strong></h1>
  </div>

  <div>
    <p><%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
      <%= f.submit "Edit", class: "btn btn-primary" %>
      <% end %></p>
  </div>

  <div>
    <p><i class="fas fa-arrow-circle-left"></i> <%= link_to "Back to All Restaurants", restaurants_path %></p>
  </div>

  <div>
    <p><i class="fas fa-trash-alt"></i> <%= link_to "Delete", restaurant_path(@restaurant),
    method: :delete,
    data: { confirm: "Are you sure?" } %></p>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="title">
    <h1><strong>Restaurants</strong></h1>
  </div>
  <div class="add-restaurant"><p><i class="fas fa-plus-circle"></i> <%= link_to "Add a Restaurant", new_restaurant_path %> </p></div>
  <div class="all-restaurants">
    <div class="row">
      <div>
        <ul>
          <% @restaurants.each do |restaurant| %>
          <li class="col-xs-12 col-sm-6 col-md-4 col-lg-3"><h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
            <p><%= restaurant.address.capitalize %></p>
            <p><%= restaurant.category.capitalize %></p></li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">

  <div class="title">
    <h1><strong>New</strong></h1>
  </div>

  <div>
    <p><%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
    <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %></p>
  </div>

  <div>
      <p><i class="fas fa-arrow-circle-left"></i> <%= link_to "Back to All Restaurants", restaurants_path %></p>
  </div>

</div>

app/views/restaurants/show.html.erb
<div class="container">

  <div class="title">
    <h1><strong><%= @restaurant.name %> </strong></h1>
  </div>
  <div class="details">
    <p><%= @restaurant.address.capitalize %> | <%= @restaurant.category.capitalize %></p>
  </div>

  <div class="buttons">
    <div>
      <p><i class="fas fa-edit"></i> <%= link_to "Edit", edit_restaurant_path %></p>
    </div>
    <div>
      <p><i class="fas fa-trash-alt"></i> <%= link_to "Delete", restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %></p>
    </div>
  </div>

  <div>
    <img src="https://www.theriverside.co.uk/images/Inside-Restaurant.jpg" class="img-rest">
  </div>

  <h3>Reviews</h3>
  <div class="reviews">
    <% @reviews.each do |review| %>
    <p> <%= review.content %> </p>
    <p> <%= review.rating %> </p>
    <% end %>
  </div>

  <h3>Do Your Review</h3>
  <div class="all-reviews">
    <div >
      <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
      <%= f.submit "Add a Review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="back-to-all">
    <p><i class="fas fa-arrow-circle-left"></i> <%= link_to "Back to All Restaurants", restaurants_path %></p>
  </div>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>